version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - network

  backend:
    image: openjdk:21
    container_name: spring-backend
    depends_on:
      - postgres
    volumes:
      - ./cpp-0.0.1-SNAPSHOT.jar:/app/cpp-0.0.1-SNAPSHOT.jar
      - ./devkit-0.0.1-SNAPSHOT.jar:/app/devkit-0.0.1-SNAPSHOT.jar
      - ./go-0.0.1-SNAPSHOT.jar:/app/go-0.0.1-SNAPSHOT.jar
      - ./java8-0.0.1-SNAPSHOT.jar:/app/java8-0.0.1-SNAPSHOT.jar
      - ./python3-0.0.1-SNAPSHOT.jar:/app/python3-0.0.1-SNAPSHOT.jar
      - ./plagiarism-app-0.0.1-SNAPSHOT.jar:/app/plagiarism-app-0.0.1-SNAPSHOT.jar
      - ./plagiarism-core-0.0.1-SNAPSHOT.jar:/app/plagiarism-core-0.0.1-SNAPSHOT.jar
    working_dir: /app
    command: ["java", "-jar", "/app/plagiarism-app-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/mydatabase
      SPRING_R2DBC_USERNAME: myuser
      SPRING_R2DBC_PASSWORD: mypassword
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_FLYWAY_USER: myuser
      SPRING_FLYWAY_PASSWORD: mypassword

    ports:
      - "8045:8045"
    networks:
      - network

networks:
  network:
    driver: bridge