spring:
  application:
    name: plagiarism-app
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/plag
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 007787898
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8045